Added --global option to perform actions for all users (#754)
pypa/pipx pull request #1088
Opened 2023-10-15 12:00 UTC by haxwithaxe

* [x] I have added an entry to `docs/changelog.md`

## Summary of changes
 Addressing issue #754. Added `--global` option to perform actions for all users. The global option is for pipx and affects all commands except `run` and `completions` by changing the base paths that are used to generate the install directories.
There are two important sets of changes. 
* One is a bare minimum implementation (first two commits).
* The other is a cleaner implementation (third commit).
  * This breaks out the paths into there own submodule since they definitely aren't constants anymore.

These changes also include new pytest tests and necessarily required changes to existing tests.

I'm perfectly happy to go with either of those or a complete rewrite if that's required to make this feature fit into this project. I'm not married to any of the implementation details.

## Test plan
Passes your CI process on github (via your unaltered actions in my fork https://github.com/haxwithaxe/pipx/actions/runs/6518200232).

### Manually tested by running
To verify the changes do what they are supposed to
```
python3 src/pipx --global environment
```

To test all the relevant commands for regressions.
```
python3 src/pipx --global ensurepath
sudo python3 src/pipx --global install pycowsay
sudo python3 src/pipx --global reinstall pycowsay
sudo python3 src/pipx --global inject pycowsay black
sudo python3 src/pipx --global uninject pycowsay black
sudo python3 src/pipx --global runpip pycowsay freeze
sudo python3 src/pipx --global list
sudo python3 src/pipx --global uninstall pycowsay
python3 src/pipx environment
python3 src/pipx ensurepath
python3 src/pipx install pycowsay
python3 src/pipx reinstall pycowsay
python3 src/pipx inject pycowsay black
python3 src/pipx uninject pycowsay black
python3 src/pipx runpip pycowsay freeze
python3 src/pipx list
python3 src/pipx uninstall pycowsay
```

2023-11-08 14:59 UTC, haxwithaxe commented
No interest in this or just not a priority? I'm happy to completely redo this in a way the devs want if there's interest but this PR isn't acceptable somehow. I truely am not married to the implementation. My goal is to have something like this functionality in a way the devs are happy with. If that includes starting from scratch with guidance I will do that.

2023-11-30 19:48 UTC, gaborbernat requested changes
No maintainer was interested in spending time on this 🤔  I'm around now, can we rebase it against main.

2023-12-08 17:50 UTC, closed without merging

2023-12-09 14:16 UTC, haxwithaxe commented
Sorry for the delayed response. Life decided to happen all at once last week. I won't likely get back to this for a week or two more but I'll do my best to get to it sooner.

2023-12-09 17:55 UTC, gaborbernat commented
No worries, take your time, we can pick it up when you're ready.

2023-12-25 15:04 UTC, haxwithaxe commented
Everything is merged and retested as described in the first post.

2024-01-01 23:11 UTC, eode commented
So, is this slated for release then?  The PR looks closed, not merged.

2024-02-08 15:40 UTC, GhostLyrics commented
Doesn't look merged. The other changelog entries that were in the diff show that it would've been in the [1.3.0 release which it wasn't](https://github.com/pypa/pipx/releases/tag/1.3.0).

2024-02-08 16:41 UTC, Gitznik commented
Yes this PR seems to have gone under the radar unfortunately. If anyone want's to pick this up again, please open a new PR and I'm happy to support this. Sorry @haxwithaxe that your first PR here did not get proper attention.

I'm not against the implementation seen here, we just need to update it to the current codebase.