Use venv Python to check pip's availability
pypa/pipx pull request #1111
Opened 2023-11-20 15:48 UTC by dukecat0

* [x] I have added an entry to `docs/changelog.md`

## Summary of changes
Use virtual environment's Python to check for pip's availability during reinstalling process.
Closes #1110 

## Test plan

Tested by running
```
nox -s test-3.11
```

2023-11-25 10:31 UTC, asyncon commented
Will this actually solve the issue of post fedora upgrade with a new minor version `3.X` of python? 

If the file `~/.local/pipx/shared/bin/python3` points to a now updated version of python, it stands to reason that some of `~/.local/pipx/venvs/*/bin/python3` might also do the same. Which would then result in the same outcome of a python version mismatch and not finding the pip module in `~/.local/pipx/shared/lib/python3.X/site-packages` because it's in `python3.$((X-1))`.

An alternate idea is to move the new the new pip module detection logic into the `pipx.shared_libs._SharedLibs.is_valid` property. 

This solution would also work for all other commands as well such as install and upgrade.

2023-12-02 05:14 UTC, gaborbernat requested changes
Merge conflicts.

2023-12-02 05:44 UTC, gaborbernat approved these changes
![](https://media.tenor.co/images/0729d8125f80f37fdc3ed6c0f874822f/tenor.gif)

2023-12-02 05:44 UTC, gaborbernat requested changes
Ah, new merge conflicts.

2023-12-02 05:46 UTC, dukecat0 commented
Fixed

2023-12-02 05:53 UTC, gaborbernat approved these changes
![](https://media.tenor.co/images/0729d8125f80f37fdc3ed6c0f874822f/tenor.gif)

2023-12-02 05:56 UTC, merged

2025-01-15 10:09 UTC, Flimm commented
As far as I can tell, this fix has yet to be released in a release of pipx.