fix: append pip errors to log file rather than overwrite
pypa/pipx pull request #1133
Opened 2023-12-03 13:31 UTC by corneliusroemer

Resolves #1132 

An alternative would be to create new log files for each pip invocation, but this would require deeper changes. Appending seems like a decent solution as a first fix.

- [x] I have added an entry to `docs/changelog.md`

## Summary of changes

## Test plan

Tested by running

```
python src/pipx install visidata pycowsay --python "3.11"
python src/pipx reinstall-all --python "3.12"
```

The logs now contain pip error output from both errors: visidata and pycowsay. Exactly what should happen.

2023-12-03 17:16 UTC, gaborbernat requested changes
Tests.

2023-12-03 18:30 UTC, corneliusroemer commented
@gaborbernat I'm struggling to think of a good way to produce multiple error messages in a deterministic way. The PR that added the log files tests the functionality by doing `pipx install weblate=4.3.1` which seems to be a package spec for which install fails, but since there's no `pipx install-all` I can't think of how to extend this to produce multiple errors. Any thoughts?

https://github.com/pypa/pipx/blob/9639e2ccf22c584154be87a431b1d878af054210/tests/test_install.py#L256-L266

The whole logfile content doesn't seem to be tested at all. Just the existence of the error log file. It could be empty and tests would pass at the moment, it seems.

2023-12-03 18:37 UTC, corneliusroemer commented
Sorry I'm not quite sure what you mean by "seeded packages".

I'm also not sure that this particular combination of packages and python versions will be a stable way to get multiple errors in the future.

2023-12-03 18:39 UTC, gaborbernat commented
These https://github.com/pypa/pipx/blob/main/testdata/tests_packages/primary_packages.txt#L1

2023-12-03 18:54 UTC, corneliusroemer commented
Hmm, there's only one expected fail that I can see `weblate==4.3.1          True    # expected fail in tests` and I'm not sure how I can reinstall a package that fails to install in the first place.

I managed to get multiple errors due to a bug that will get fixed eventually. The only way I can think of getting multiple errors is an upgrade where the old versions installed, but the new latest ones throw errors.

This would require _two_ packages that fail for the latest version in perpetuity. Not sure something like that exists on Pypi.

2023-12-04 14:44 UTC, gaborbernat commented
Ok 👌

2024-01-31 00:47 UTC, gaborbernat commented
Seems stalled, we can reopen if you pick it up again.

2024-01-31 00:47 UTC, closed without merging