Verify if script name provided is a file before running it
pypa/pipx pull request #1155
Opened 2023-12-18 12:43 UTC by dukecat0

- [x] I have added an entry to `docs/changelog.md`

## Summary of changes
`pipx run`: Verify whether the script name provided is a file before running it
Closes https://github.com/pypa/pipx/issues/1152

## Test plan

Tested by running

```
nox -s tests-3.12
```

2023-12-18 15:04 UTC, chrysle commented
Didn't you want to detect whether the file is a valid script?

2023-12-19 08:59 UTC, uranusjr commented on src/pipx/commands/run.py
> +    if app_path.exists() and app_path.is_file():
```suggestion
    if app_path.is_file():
```

I believe `is_file` implies `exists`.

https://docs.python.org/3/library/pathlib.html#pathlib.Path.is_file

> False is also returned if the path doesn’t exist […].

2023-12-26 10:23 UTC, dukecat0 commented
> Didn't you want to detect whether the file is a valid script?

I think a file that has no `.py` extension or shebang can be a valid script as well. (At least the Python interpreter doesn't care about it.) That's why I personally believe that checking whether it is a file is enough.

2023-12-28 00:38 UTC, gaborbernat requested changes
Test please 👍

2023-12-29 09:54 UTC, dukecat0 commented
Not sure if we need a test for this...? I personally think this is a very minor bug and doesn't require a test.

2024-01-08 15:16 UTC, gaborbernat commented
> Not sure if we need a test for this...? I personally think this is a very minor bug and doesn't require a test.

I disagree.

2024-01-08 15:17 UTC, gaborbernat requested changes
Tests please.

2024-01-09 08:20 UTC, dukecat0 commented
> Tests please.

Added

2024-01-10 16:19 UTC, gaborbernat approved these changes

2024-01-10 16:19 UTC, merged