Allow skipping maintenance tasks for list command
pypa/pipx pull request #1163
Opened 2023-12-22 20:26 UTC by Gitznik

- [X] I have added an entry to `docs/changelog.md`

## Summary of changes
Add a `--skip-maintenance` flag to the list command. This sets a new state on the `_SharedLibs` class, that is used to skip the shared libs upgrade step by setting `needs_upgrade` to False. This change allows the user to skip the functionality that reaches out to `pip`, which makes executing the command a lot faster when offline.
resolves #1081 

## Test plan

Introduced a new test case `test_skip_maintenance`. It first adds some commands to introduce shared libs. It then verifies that a normal `list` command set's the expected state on the `shared_libs` object and then verifies that running `list` with `--skip-maintenance` results in state on the `shared_libs` object that indicates that no upgrade was performed.

Tested by running `nox -s tests-3.12`

```
pipx list --skip-maintenance
```

2023-12-23 14:42 UTC, chrysle reviewed
Concerning the test, probably really collect the times after running the CLI, and compare the durations.

2023-12-23 14:42 UTC, chrysle commented on src/pipx/commands/list_packages.py
> +        shared_libs.shared_libs.skip_maintenance = True
Maybe rename this to `skip_upgrade`... I don't think it's a problem to be more concise internally.

2023-12-23 16:33 UTC, Gitznik commented
> Concerning the test, probably really collect the times after running the CLI, and compare the durations.

I did this manually:
`python3 src/pipx list --skip-maintenance  0.42s user 0.14s system 87% cpu 0.638 total`
vs with maintenance
`python3 src/pipx list  0.72s user 0.21s system 10% cpu 8.623 total`
when running offline and being in a state that would require an upgrade.

Do you have a suggestion on how to automate this with a test? My only suggestion would be to modify `pipx_temp_env` to allow creating an unresponsive local pypi server, but that feels like a lot of custom logic for one test.

2023-12-25 09:48 UTC, uranusjr approved these changes

2023-12-28 00:39 UTC, gaborbernat approved these changes
![](https://media.tenor.co/images/15c955585420695acab185a96d094a82/tenor.gif)

2023-12-28 00:42 UTC, gaborbernat requested changes
Needs merge conflicts fixed and rebased.

2023-12-29 15:48 UTC, Gitznik commented
> Needs merge conflicts fixed and rebased.

Done

2023-12-30 09:28 UTC, dukecat0 submitted a review, later dismissed

2024-01-04 00:25 UTC, merged