fix: nicer tracebacks in run mode on scripts
pypa/pipx pull request #1191
Opened 2024-01-05 16:32 UTC by henryiii

This is one way to improve the tracebacks as reported in #1187.

- [ ] I have added an entry to `docs/changelog.md`

## Summary of changes

This is the simplest way I initially see to get filenames. Instead of passing around the contents of the script as a string, scripts are passed around as Paths, which allows the run command to run the path rather than passing the string on the command line.

## Test plan

If you start with this script:

```python
import httpx
```

You get this:

```console
$ pipx run ./script.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'
```

After this PR, you get this:

```console
$ pipx run ./script.py
Traceback (most recent call last):
  File "/Users/henryschreiner/git/software/pipx/script.py", line 1, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'
```

2024-01-05 17:01 UTC, flying-sheep requested changes
Looks lovely! I think there could be some slight deduplication, otherwise wonderful!

2024-01-05 17:01 UTC, flying-sheep commented on src/pipx/commands/run.py
> +            exec_app([venv.python_path, "-c", content, *app_args])
```suggestion
        python_path = venv.python_path

    if isinstance(content, Path):
        exec_app([python_path, content, *app_args])
    else:
        exec_app([python_path, "-c", content, *app_args])
```

2024-01-05 18:10 UTC, henryiii commented on src/pipx/commands/run.py
> +        python_path = python
```suggestion
        python_path = Path(python)
```

2024-01-05 20:09 UTC, chrysle submitted a review, later dismissed
Looks good!

2024-01-05 20:14 UTC, chrysle commented
I think we should really enable merge queues, this constant branch updating is annoying.

2024-01-07 06:54 UTC, rsalmaso commented
Happy for this patch!

Running script instead of string solve another problem: run the script via shebang `#!/usr/bin/env -S pipx run` and get the correct filename `sys.argv[0]`.

2024-01-07 07:47 UTC, dukecat0 requested changes
Test please, otherwise LGTM.

2024-01-10 22:05 UTC, henryiii commented
What should this do if a URI is passed, by the way? Currently that still says "<string>". That could be a future improvement, but something to think about.

2024-01-11 05:36 UTC, dukecat0 commented
> What should this do if a URI is passed, by the way? Currently that still says "<string>". That could be a future improvement, > but something to think about.

Perhaps we can have an additional check here?
https://github.com/pypa/pipx/blob/5563ae68aecda0b36e59979bcbd8e81a96ec3fbd/src/pipx/commands/run.py#L57

2024-01-12 21:26 UTC, henryiii commented
A check wouldn't help, we are already doing the "right" think (since when getting a URI it needs to be downloaded, possibly from a remote source), it's just then a question of if there's a way to get it to show something nicer than "<string>". This was fixable since loading a local file can just be directly run by the `python` command. I would assume there's a way to customize running on arbitrary input, since things like IPython do it (though at in least some cases, they write out temporary files).

2024-01-14 19:31 UTC, gaborbernat requested changes
Let's rebase and add changelog.

2024-01-15 16:53 UTC, dukecat0 approved these changes

2024-01-16 16:20 UTC, merged