Fix typo in README.md - hatch
pypa/pipx pull request #1218
Opened 2024-01-18 17:57 UTC by ezhang7423

- [ ] I have added a news fragment under `changelog.d/` (if the patch affects the end users)

## Summary of changes

## Test plan

Tested by running

```
# command(s) to exercise these changes
```

2024-01-18 18:10 UTC, Gitznik requested changes
Thanks for contributing to the docs :)

2024-01-18 18:10 UTC, Gitznik commented on README.md
> +if you're using hatch, [try this](https://hatch.pypa.io/latest/config/metadata/#cli).
Please also add a comma after `Or`.

2024-01-19 05:56 UTC, uranusjr approved these changes

2024-01-19 07:01 UTC, Gitznik approved these changes

2024-01-19 07:11 UTC, merged