Update requirement specification
pypa/pipx pull request #1240
Opened 2024-02-03 08:25 UTC by oberbichler

- [ ] I have added a news fragment under `changelog.d/` (if the patch affects the end users)

## Summary of changes

- Update documentation for `pipx run` with dependencies in a local script (see #1227)

## Test plan

Tested by running

```python
# test.py

# /// script
# dependencies = ["requests"]
# ///

import sys
import requests
project = sys.argv[1]
pipx_data = requests.get(f"https://pypi.org/pypi/{project}/json").json()
print(pipx_data["info"]["version"])
```
with

```bash
pipx run test.py
```

2024-02-03 09:20 UTC, Gitznik requested changes
Thanks for updating this. Could you please add a `doc` news fragment according to our [contribution guidelines](https://pipx.pypa.io/stable/contributing/#changelog-entries)?

2024-02-03 09:52 UTC, oberbichler commented
Done

2024-02-03 10:29 UTC, chrysle commented
Please also mention that the requirement specification syntax comes from the [inline script metadata specification](https://packaging.python.org/en/latest/specifications/inline-script-metadata/).

2024-02-05 10:41 UTC, Gitznik commented
> Please also mention that the requirement specification syntax comes from the [inline script metadata specification](https://packaging.python.org/en/latest/specifications/inline-script-metadata/).

As per @katrinafyi in https://github.com/pypa/pipx/pull/1244:

```
If you have a script `test.py` that needs 3rd party libraries,
you can add [inline script metadata](https://packaging.python.org/en/latest/specifications/inline-script-metadata/)
in the style of PEP 723.
```

2024-02-06 17:38 UTC, oberbichler commented
Done

2024-02-06 17:46 UTC, Gitznik approved these changes
Looks good, thank you

2024-02-06 20:15 UTC, merged

2024-02-06 20:16 UTC, chrysle commented
Thanks!