Add interpreter command
pypa/pipx pull request #1261
Opened 2024-02-22 18:10 UTC by Gitznik

- [x] I have added a news fragment under `changelog.d/` (if the patch affects the end users)

## Summary of changes

Add a `interpreter` command with `list` and `prune` subcommand. They can be used to list the installed standalone interpreters and prune unused standalone interpreters.
Resolves #1248 

## Test plan

Tested by running

```
pipx install --fetch-missing-python --python 3.7 pycowsay
pipx interpreter list
pipx uninstall pycowsay
pipx interpreter prune
```

2024-02-25 08:25 UTC, dukecat0 requested changes
Besides, running `pipx interpreter` without any arguments will result in an error:
```
Unknown interpreter command None
```

2024-02-25 11:29 UTC, Gitznik commented on src/pipx/commands/interpreter.py
> +    def is_paths_relative(path: Path, parent: Path):
Sure

2024-02-25 11:30 UTC, Gitznik commented
> Besides, running `pipx interpreter` without any arguments will result in an error:
> 
> ```
> Unknown interpreter command None
> ```

I've now adapted the logic from running `pipx` without a subcommand. Unfortunately that means passing around the subparser, to be able to call `print_help` on it. There is no public API to retrieve the subparsers from the main parser unfortunately.

2024-02-26 05:41 UTC, dukecat0 approved these changes

2024-02-26 07:21 UTC, merged