Issue #1535 - Add a `help` command (alias of `--help`)
pypa/pipx pull request #1544
Opened 2024-09-10 22:32 UTC by timacias

- [x] I have added a news fragment under `changelog.d/` (if the patch affects the end users)

## Summary of changes
1. `pipx --help` and `pipx [command_name] --help` both produce help info.
2. Issue #1535 requests a new pipx command that is an alias for `--help`.
3. `pipx help` and `pipx help [command_name]` can now be used to provide identical output to (1).
4. The help info now references the new help command.

## Test plan

Tested by running

```
# command(s) to exercise these changes
python3 src/pipx help
python3 src/pipx help install
python3 src/pipx help pin

# if pipx is installed to your system
pipx help
pipx help install
pipx help pin
```

This is my first PR to a public repo. Please feel free to let me know if there are any guidelines or general tenets I've failed to follow. Thanks!

2024-09-17 07:25 UTC, Gitznik requested changes
Thanks for your contribution :muscle: can you please add some tests for this?
Also can you verify this will work with commands with multiple subcommands, like `pipx interpreter list`?

2024-09-17 07:25 UTC, Gitznik commented on src/pipx/main.py
> +        dest="command", description="Get help for commands with pipx COMMAND --help\n\t\t\t  or pipx help COMMAND"
Please stick to how the other commands wrap text in their description.

2024-09-25 23:38 UTC, timacias commented
Thanks for your comment. I have added a fix for cases with multiple subcomamnds (e.g., `pipx interpreter list` and `pipx interpreter prune`) . I'll add tests for the help subcommand in my next commit.

2024-09-28 02:50 UTC, totall4u commented
> - [x] I have added a news fragment under `changelog.d/` (if the patch affects the end users)
> 
> 
> 
> ## Summary of changes
> 
> 1. `pipx --help` and `pipx [command_name] --help` both produce help info.
> 
> 2. Issue #1535 requests a new pipx command that is an alias for `--help`.
> 
> 3. `pipx help` and `pipx help [command_name]` can now be used to provide identical output to (1).
> 
> 4. The help info now references the new help command.
> 
> 
> 
> ## Test plan
> 
> 
> 
> <!-- provide evidence of testing, preferably with command(s) that can be copy+pasted by others -->
> 
> 
> 
> Tested by running
> 
> 
> 
> ```
> 
> # command(s) to exercise these changes
> 
> python3 src/pipx help
> 
> python3 src/pipx help install
> 
> python3 src/pipx help pin
> 
> 
> 
> # if pipx is installed to your system
> 
> pipx help
> 
> pipx help install
> 
> pipx help pin
> 
> ```
> 
> 
> 
> This is my first PR to a public repo. Please feel free to let me know if there are any guidelines or general tenets I've failed to follow. Thanks!

2024-10-04 07:16 UTC, Gitznik requested changes
Generally, looks fine for me. Please make all pipelines pass, I'll give it another proper review once that's done.

2024-10-09 07:47 UTC, Gitznik requested changes
Just played around with this locally. If running `pipx help`, the autocomplete does not work anymore unfortunately. Could you have a look at that please?

2026-03-18 13:27 UTC, gaborbernat requested changes
Can you rebase and fix the merge conflicts?

2026-05-05 15:46 UTC, gaborbernat commented
Seems stalled we can re-open if you get back to it.

2026-05-05 15:46 UTC, closed without merging