Update *Edit this page* link (#760)
pypa/pipx pull request #761
Opened 2021-11-16 11:42 UTC by NdagiStanley

* [x] I have added an entry to `docs/changelog.md`

## Summary of changes

- Updated `mkdocs.yml` to include

Reference: [MkDocs User guide configuration page](https://www.mkdocs.org/user-guide/configuration/#edit_uri)

## Test plan

Tested by running the following in a python virtual environment:
```
pip install nox
nox -s watch_docs
```

The updated docs can be viewed at [http://127.0.0.1:8000/](http://127.0.0.1:8000/). Click on the pencil icon towards the top right part of the page and confirm that the link redirects to [this page](https://github.com/pypa/pipx/edit/main/docs/index.md)

<img width="1777" alt="Screenshot 2021-11-16 at 14 16 09" src="https://user-images.githubusercontent.com/15629602/141975922-f6bd63d0-6b8b-4ff1-8878-0417b30f5233.png">

2021-11-16 11:43 UTC, NdagiStanley commented
Closes #760

2021-11-16 13:00 UTC, uranusjr approved these changes

2022-01-02 15:08 UTC, gaborbernat requested changes
Merge conflicts need to be resolved.

2022-01-03 06:59 UTC, NdagiStanley commented
@gaborbernat I've resolved the merge conflicts.

This can be added to the `docs/changelog.md`:

```
- Updated *Edit this page* link in the documentation pages to redirect to the `main` branch instead of the (non-existent) `master` branch.
```

2022-01-03 11:03 UTC, merged

2022-01-03 11:04 UTC, gaborbernat commented on src/pipx/commands/reinstall.py
> +    if python_relative_to_venv_dir:
This change seems unrelated, what happened here?

2022-01-03 11:06 UTC, gaborbernat commented on src/pipx/commands/reinstall.py
> +    if python_relative_to_venv_dir:
I've reverted the PR to avoid merging this. Please open a new PR and keep the change set scopped to the PR description.